"""
ATLAS Web Server — Dashboard & JSON API.

Serves expanded web reports generated by the ATLAS engine.
No LLM calls. Renders deterministic data from SQLite.

Run locally:
    uvicorn web_server:app --reload --port 8000

Routes:
    GET /r/{report_id}          → HTML dashboard (Tailwind + Chart.js CDN)
    GET /api/r/{report_id}.json → Raw payload JSON
    GET /health                 → Health check
"""

import json
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse

from web_report import get_report

app = FastAPI(title="ATLAS Web Reports", docs_url=None, redoc_url=None)


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------
@app.get("/health")
def health():
    return {"status": "ok"}


# ---------------------------------------------------------------------------
# JSON API
# ---------------------------------------------------------------------------
@app.get("/api/r/{report_id}.json")
def api_report(report_id: str):
    payload = get_report(report_id)
    if payload is None:
        raise HTTPException(status_code=404, detail="Report not found")
    return JSONResponse(content=payload)


# ---------------------------------------------------------------------------
# HTML Dashboard
# ---------------------------------------------------------------------------
@app.get("/r/{report_id}", response_class=HTMLResponse)
def html_report(report_id: str):
    payload = get_report(report_id)
    if payload is None:
        raise HTTPException(status_code=404, detail="Report not found")

    # Embed payload as JSON inside the HTML so the page is self-contained
    payload_json_escaped = json.dumps(payload).replace("</", "<\\/")

    html = _build_dashboard_html(report_id, payload_json_escaped)
    return HTMLResponse(content=html)


# ---------------------------------------------------------------------------
# Dashboard HTML builder (single-page, CDN-only, no build step)
# ---------------------------------------------------------------------------
def _build_dashboard_html(report_id: str, payload_json_escaped: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en" class="bg-gray-950 text-gray-100">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ATLAS Report</title>
<script src="https://cdn.tailwindcss.com"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js"></script>
<style>
  body {{ font-family: 'Inter', system-ui, -apple-system, sans-serif; }}
  .card {{ @apply bg-gray-900 rounded-xl border border-gray-800 p-5 mb-4; }}
  .badge {{ @apply inline-block px-2 py-0.5 rounded text-xs font-semibold; }}
</style>
</head>
<body class="min-h-screen p-4 md:p-8 max-w-6xl mx-auto">

<!-- Populated by JS from embedded payload -->
<div id="app">
  <p class="text-gray-500 text-center mt-20">Loading report&hellip;</p>
</div>

<script>
// Embedded payload — no extra fetch required
const DATA = {payload_json_escaped};

// ── Helpers ──────────────────────────────────────────────────────────
const fmt  = (v, d=1) => v == null ? 'N/A' : Number(v).toFixed(d);
const fmtP = (v, d=1) => v == null ? 'N/A' : (v >= 0 ? '+' : '') + Number(v).toFixed(d) + '%';
const fmtM = (v) => {{
  if (v == null) return 'N/A';
  const abs = Math.abs(v);
  if (abs >= 1e12) return '$' + (v/1e12).toFixed(2) + 'T';
  if (abs >= 1e9)  return '$' + (v/1e9).toFixed(2) + 'B';
  if (abs >= 1e6)  return '$' + (v/1e6).toFixed(1) + 'M';
  return '$' + v.toLocaleString();
}};
const safe = (obj, ...keys) => {{
  let cur = obj;
  for (const k of keys) {{ if (cur == null) return null; cur = cur[k]; }}
  return cur;
}};

// ── Verdict colour ───────────────────────────────────────────────────
function verdictColor(score) {{
  if (score >= 60) return 'text-emerald-400';
  if (score >= 40) return 'text-yellow-400';
  return 'text-red-400';
}}
function verdictBg(score) {{
  if (score >= 60) return 'bg-emerald-500/20 text-emerald-300';
  if (score >= 40) return 'bg-yellow-500/20 text-yellow-300';
  return 'bg-red-500/20 text-red-300';
}}

// ── Score bar (10 blocks) ────────────────────────────────────────────
function scoreBar(score, max=100) {{
  const pct = Math.max(0, Math.min(100, ((score + max) / (2 * max)) * 100));
  const filled = Math.round(pct / 10);
  return '<span class="font-mono text-xs">' +
    '<span class="text-emerald-400">' + '█'.repeat(filled) + '</span>' +
    '<span class="text-gray-700">' + '░'.repeat(10 - filled) + '</span>' +
    '</span>';
}}

// ── Build page ───────────────────────────────────────────────────────
function render() {{
  const s   = DATA.summary || {{}};
  const v8  = DATA.v8_extended || {{}};
  const prov = DATA.provenance || {{}};
  const co  = v8.company || {{}};
  const fin = v8.financials || {{}};
  const tech = v8.technicals || {{}};
  const peers = v8.peers || [];
  const dcf  = v8.dcf || null;
  const scores = s.scores || {{}};
  const wDyn = s.w_dynamic || {{}};
  const contribs = s.contributions || {{}};

  const composite = s.composite_adjusted != null ? s.composite_adjusted : s.composite_raw;
  const compositeRaw = s.composite_raw;
  const compositeAdj = s.composite_adjusted;
  const tq = s.trade_quality;
  const dc = s.data_confidence;
  const regime = s.regime_label || 'N/A';
  const reliability = s.regime_reliability;
  const execMode = s.execution_mode || 'N/A';
  const verdict = s.verdict || 'N/A';
  const price = s.price || co.price;
  const companyName = DATA.company_name || co.name || DATA.symbol;

  // Normalise composite to 0-100 for colour
  const normScore = composite != null ? Math.max(0, Math.min(100, (composite + 100) / 2)) : 50;

  let html = '';

  // ── Header ─────────────────────────────────────────────────────────
  html += `
  <div class="mb-6">
    <div class="flex flex-wrap items-baseline gap-3 mb-1">
      <h1 class="text-3xl font-bold tracking-tight">${{DATA.symbol}}</h1>
      <span class="text-lg text-gray-400">${{companyName}}</span>
    </div>
    <div class="text-sm text-gray-500">
      ATLAS V8 &middot; ${{new Date(DATA.created_at).toLocaleString()}}
      ${{prov.fallback_mode ? ' &middot; Data: ' + prov.fallback_mode : ''}}
    </div>
  </div>`;

  // ── Key Metrics Row ────────────────────────────────────────────────
  html += `<div class="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-3 mb-6">`;
  const metrics = [
    ['Verdict', verdict, verdictBg(normScore)],
    ['Composite', (compositeAdj != null ? fmt(compositeAdj,1) : 'N/A') + ' / 100', verdictBg(normScore)],
    ['Raw Score', compositeRaw != null ? fmt(compositeRaw,1) : 'N/A', 'bg-gray-800 text-gray-300'],
    ['Trade Quality', tq != null ? fmt(tq, 3) : 'N/A', 'bg-gray-800 text-gray-300'],
    ['Regime', regime, 'bg-gray-800 text-gray-300'],
    ['Data Conf.', dc != null ? fmt(dc,0) + '%' : 'N/A', 'bg-gray-800 text-gray-300'],
  ];
  for (const [label, value, cls] of metrics) {{
    html += `<div class="card !p-3 text-center">
      <div class="text-[11px] text-gray-500 uppercase tracking-wider mb-1">${{label}}</div>
      <div class="badge ${{cls}}">${{value}}</div>
    </div>`;
  }}
  html += `</div>`;

  // ── Engine Scores Table ────────────────────────────────────────────
  const engineNames = ['trend','valuation','consensus','volatility','macro','liquidity','global','correlation'];
  html += `<div class="card">
    <h2 class="text-lg font-semibold mb-3">Engine Scores</h2>
    <div class="overflow-x-auto">
    <table class="w-full text-sm">
      <thead><tr class="text-gray-500 text-xs uppercase">
        <th class="text-left py-1 pr-4">Engine</th>
        <th class="text-right pr-4">Score</th>
        <th class="text-center pr-4">Bar</th>
        <th class="text-right pr-4">Weight</th>
        <th class="text-right">Contribution</th>
      </tr></thead><tbody>`;
  let totalContrib = 0;
  for (const eng of engineNames) {{
    const sc = scores[eng];
    const w  = wDyn[eng];
    const ct = contribs[eng];
    if (ct != null) totalContrib += ct;
    html += `<tr class="border-t border-gray-800">
      <td class="py-1.5 pr-4 font-medium">${{eng}}</td>
      <td class="text-right pr-4 ${{sc >= 0 ? 'text-emerald-400' : 'text-red-400'}}">${{sc != null ? (sc >= 0 ? '+' : '') + fmt(sc,1) : 'N/A'}}</td>
      <td class="text-center pr-4">${{sc != null ? scoreBar(sc) : ''}}</td>
      <td class="text-right pr-4 text-gray-400">${{w != null ? fmt(w, 3) : ''}}</td>
      <td class="text-right ${{ct >= 0 ? 'text-emerald-400' : 'text-red-400'}}">${{ct != null ? (ct >= 0 ? '+' : '') + fmt(ct, 2) : ''}}</td>
    </tr>`;
  }}
  html += `<tr class="border-t-2 border-gray-700 font-bold">
    <td class="py-1.5" colspan="4">TOTAL</td>
    <td class="text-right ${{totalContrib >= 0 ? 'text-emerald-400' : 'text-red-400'}}">${{(totalContrib >= 0 ? '+' : '') + fmt(totalContrib, 2)}}</td>
  </tr>`;
  html += `</tbody></table></div></div>`;

  // ── Trade Plan ─────────────────────────────────────────────────────
  if (s.stop_loss || s.entry) {{
    html += `<div class="card">
      <h2 class="text-lg font-semibold mb-3">Trade Plan</h2>
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 text-sm">`;
    const tp = [
      ['Price', price != null ? '$' + fmt(price, 2) : 'N/A'],
      ['Entry', s.entry ? '$' + fmt(s.entry, 2) : 'N/A'],
      ['Stop Loss', s.stop_loss ? '$' + fmt(s.stop_loss, 2) : 'N/A'],
      ['Mode', execMode],
      ['Buy Zone', s.buy_zone ? '$' + fmt(s.buy_zone[0],2) + ' – $' + fmt(s.buy_zone[1],2) : 'N/A'],
      ['Target', s.take_profit ? '$' + fmt(s.take_profit[0],2) + ' – $' + fmt(s.take_profit[1],2) : 'N/A'],
      ['Position $', s.position_size ? fmtM(s.position_size) : 'N/A'],
      ['Position %', s.position_pct != null ? fmt(s.position_pct,1) + '%' : 'N/A'],
    ];
    for (const [label, value] of tp) {{
      html += `<div><div class="text-[11px] text-gray-500 uppercase">${{label}}</div><div class="font-medium">${{value}}</div></div>`;
    }}
    html += `</div></div>`;
  }}

  // ── DCF Scenarios ──────────────────────────────────────────────────
  if (dcf && (dcf.bear || dcf.base || dcf.bull)) {{
    html += `<div class="card">
      <h2 class="text-lg font-semibold mb-3">DCF Fair Value Scenarios</h2>
      <div class="grid grid-cols-3 gap-4 text-center">`;
    const scenarios = [
      ['Bear', dcf.bear, 'border-red-500/40'],
      ['Base', dcf.base, 'border-yellow-500/40'],
      ['Bull', dcf.bull, 'border-emerald-500/40'],
    ];
    for (const [label, val, border] of scenarios) {{
      const upside = (price && val) ? (((val - price) / price) * 100) : null;
      html += `<div class="rounded-lg border ${{border}} bg-gray-800/50 p-4">
        <div class="text-xs text-gray-500 uppercase mb-1">${{label}}</div>
        <div class="text-xl font-bold">${{val != null ? '$' + fmt(val, 2) : 'N/A'}}</div>
        ${{upside != null ? '<div class="text-xs mt-1 ' + (upside >= 0 ? 'text-emerald-400' : 'text-red-400') + '">' + fmtP(upside, 1) + ' vs current</div>' : ''}}
      </div>`;
    }}
    html += `</div>`;
    if (dcf.assumptions) {{
      const a = dcf.assumptions;
      html += `<div class="mt-3 text-xs text-gray-500">
        Assumptions: Rev Growth ${{fmt(a.revenue_growth_y1,1)}}% &middot;
        FCF Margin ${{fmt(a.fcf_margin,1)}}% &middot;
        WACC ${{fmt(a.discount_rate,1)}}% &middot;
        Terminal ${{fmt(a.terminal_growth,1)}}%
      </div>`;
    }}
    html += `</div>`;
  }}

  // ── Peers Table ────────────────────────────────────────────────────
  if (peers.length > 0) {{
    html += `<div class="card">
      <h2 class="text-lg font-semibold mb-3">Peer Comparison</h2>
      <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead><tr class="text-gray-500 text-xs uppercase">
          <th class="text-left py-1">Ticker</th>
          <th class="text-right">Price</th>
          <th class="text-right">Mkt Cap</th>
          <th class="text-right">Rev Gr</th>
          <th class="text-right">Margin</th>
          <th class="text-right">Fwd PE</th>
          <th class="text-right">ROE</th>
        </tr></thead><tbody>`;
    // Add the subject ticker first
    html += `<tr class="border-t border-gray-800 bg-gray-800/50 font-semibold">
      <td class="py-1.5">${{DATA.symbol}}</td>
      <td class="text-right">${{price != null ? '$' + fmt(price,2) : 'N/A'}}</td>
      <td class="text-right">${{fmtM(fin.market_cap || co.market_cap)}}</td>
      <td class="text-right">${{fin.revenue_growth != null ? fmtP(fin.revenue_growth) : 'N/A'}}</td>
      <td class="text-right">${{fin.net_margin != null ? fmt(fin.net_margin,1) + '%' : 'N/A'}}</td>
      <td class="text-right">${{fin.forward_pe != null ? fmt(fin.forward_pe,1) + 'x' : 'N/A'}}</td>
      <td class="text-right">${{fin.roe != null ? fmt(fin.roe,1) + '%' : 'N/A'}}</td>
    </tr>`;
    for (const p of peers) {{
      html += `<tr class="border-t border-gray-800">
        <td class="py-1.5">${{p.symbol || ''}}</td>
        <td class="text-right">${{p.price != null ? '$' + fmt(p.price,2) : 'N/A'}}</td>
        <td class="text-right">${{fmtM(p.market_cap)}}</td>
        <td class="text-right">${{p.revenue_growth != null ? fmtP(p.revenue_growth) : 'N/A'}}</td>
        <td class="text-right">${{p.profit_margin != null ? fmt(p.profit_margin,1) + '%' : 'N/A'}}</td>
        <td class="text-right">${{p.forward_pe != null ? fmt(p.forward_pe,1) + 'x' : 'N/A'}}</td>
        <td class="text-right">${{p.roe != null ? fmt(p.roe,1) + '%' : 'N/A'}}</td>
      </tr>`;
    }}
    html += `</tbody></table></div></div>`;
  }}

  // ── Technicals ─────────────────────────────────────────────────────
  if (tech.sma20 || tech.rsi_14) {{
    html += `<div class="card">
      <h2 class="text-lg font-semibold mb-3">Technical Indicators</h2>
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 text-sm mb-4">`;
    const techMetrics = [
      ['RSI (14)', tech.rsi_14 != null ? fmt(tech.rsi_14,1) : 'N/A'],
      ['MACD', tech.macd_line != null ? fmt(tech.macd_line,3) : 'N/A'],
      ['ADX', tech.adx != null ? fmt(tech.adx,1) : 'N/A'],
      ['OBV Trend', tech.obv_trend || 'N/A'],
      ['SMA 20', tech.sma20 != null ? '$' + fmt(tech.sma20,2) : 'N/A'],
      ['SMA 50', tech.sma50 != null ? '$' + fmt(tech.sma50,2) : 'N/A'],
      ['SMA 200', tech.sma200 != null ? '$' + fmt(tech.sma200,2) : 'N/A'],
      ['ATR', tech.atr != null ? '$' + fmt(tech.atr,2) : 'N/A'],
    ];
    for (const [label, value] of techMetrics) {{
      html += `<div><div class="text-[11px] text-gray-500 uppercase">${{label}}</div><div class="font-medium">${{value}}</div></div>`;
    }}
    html += `</div>`;

    // Support / Resistance levels
    const supports = tech.support_levels || [];
    const resistances = tech.resistance_levels || [];
    if (supports.length || resistances.length) {{
      html += `<div class="grid grid-cols-2 gap-4 text-sm">
        <div><div class="text-xs text-gray-500 uppercase mb-1">Resistance</div>`;
      for (const r of resistances.slice(0,3)) html += `<div class="text-red-400">$${fmt(r,2)}</div>`;
      html += `</div><div><div class="text-xs text-gray-500 uppercase mb-1">Support</div>`;
      for (const sp of supports.slice(0,3)) html += `<div class="text-emerald-400">$${fmt(sp,2)}</div>`;
      html += `</div></div>`;
    }}
    html += `</div>`;
  }}

  // ── Price Chart (SMA overlay) ──────────────────────────────────────
  // We show a simple current-price vs SMAs comparison bar chart
  if (price && (tech.sma20 || tech.sma50 || tech.sma200)) {{
    html += `<div class="card">
      <h2 class="text-lg font-semibold mb-3">Price vs Moving Averages</h2>
      <div style="height:260px"><canvas id="priceChart"></canvas></div>
    </div>`;
  }}

  // ── Provenance ─────────────────────────────────────────────────────
  html += `<div class="card !bg-gray-900/50 text-xs text-gray-500 flex flex-wrap gap-x-6 gap-y-1">
    <span>Engine: ATLAS V8</span>
    <span>Reliability: ${{reliability != null ? fmt(reliability,2) : 'N/A'}}</span>
    <span>Mode: ${{execMode}}</span>
    <span>TQ Category: ${{s.tq_category || 'N/A'}}</span>
    ${{prov.latency_sec ? '<span>Latency: ' + fmt(prov.latency_sec, 1) + 's</span>' : ''}}
    ${{prov.timestamp_utc ? '<span>Generated: ' + prov.timestamp_utc + '</span>' : ''}}
    <span class="ml-auto">This is model output, NOT financial advice.</span>
  </div>`;

  document.getElementById('app').innerHTML = html;

  // ── Render Chart ───────────────────────────────────────────────────
  const chartEl = document.getElementById('priceChart');
  if (chartEl) {{
    const labels = [];
    const values = [];
    const colors = [];
    const items = [
      ['SMA 200', tech.sma200, 'rgba(239,68,68,0.7)'],
      ['SMA 50',  tech.sma50,  'rgba(234,179,8,0.7)'],
      ['SMA 20',  tech.sma20,  'rgba(59,130,246,0.7)'],
      ['Price',   price,       'rgba(16,185,129,0.9)'],
    ];
    for (const [l, v, c] of items) {{
      if (v != null) {{ labels.push(l); values.push(v); colors.push(c); }}
    }}
    new Chart(chartEl, {{
      type: 'bar',
      data: {{
        labels,
        datasets: [{{ data: values, backgroundColor: colors, borderRadius: 6, barThickness: 40 }}]
      }},
      options: {{
        responsive: true,
        maintainAspectRatio: false,
        plugins: {{
          legend: {{ display: false }},
          tooltip: {{ callbacks: {{ label: ctx => '$' + ctx.parsed.y.toFixed(2) }} }}
        }},
        scales: {{
          y: {{
            grid: {{ color: 'rgba(255,255,255,0.05)' }},
            ticks: {{ color: '#9ca3af', callback: v => '$' + v }}
          }},
          x: {{ grid: {{ display: false }}, ticks: {{ color: '#9ca3af' }} }}
        }}
      }}
    }});
  }}
}}

render();
</script>
</body>
</html>"""
