"""
ATLAS Web Server — Dashboard & JSON API.

Serves expanded web reports generated by the ATLAS engine.
No LLM calls. Renders deterministic data from SQLite.

Run locally:
    uvicorn web_server:app --reload --port 8000

Routes:
    GET /r/{report_id}          → HTML dashboard (ECharts + Tailwind CDN)
    GET /health                 → Health check
    GET /robots.txt             → Disallow all crawlers
"""

import json
import re
from pathlib import Path
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse, PlainTextResponse
from starlette.middleware.gzip import GZipMiddleware

from web_report import get_report

_REPORT_ID_RE = re.compile(r'^[A-Za-z0-9_-]{1,120}$')

# Load dashboard template once at startup
_DASHBOARD_TEMPLATE = (Path(__file__).parent / "dashboard.html").read_text()

app = FastAPI(title="ATLAS Web Reports", docs_url=None, redoc_url=None)

# GZip compression for large HTML responses
app.add_middleware(GZipMiddleware, minimum_size=1000)


@app.middleware("http")
async def security_headers(request: Request, call_next):
    response = await call_next(request)
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
    response.headers["Content-Security-Policy"] = (
        "default-src 'self'; "
        "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
        "font-src https://fonts.gstatic.com; "
        "img-src 'self' data:; "
        "connect-src 'self'"
    )
    # Private, no-store for report pages
    if request.url.path.startswith("/r/"):
        response.headers["Cache-Control"] = "private, no-store"
    return response


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/robots.txt", response_class=PlainTextResponse)
def robots_txt():
    return "User-agent: *\nDisallow: /"


@app.get("/r/{report_id}", response_class=HTMLResponse)
def html_report(report_id: str):
    if not _REPORT_ID_RE.match(report_id):
        raise HTTPException(status_code=400, detail="Invalid report ID")
    payload = get_report(report_id)
    if payload is None:
        raise HTTPException(status_code=404, detail="Report not found")
    payload_json_escaped = json.dumps(payload).replace("</", "<\\/")
    html = _DASHBOARD_TEMPLATE.replace("__PAYLOAD_JSON__", payload_json_escaped)
    return HTMLResponse(content=html)
